### ISSUE TITLE
NoSuchMethodError: Class 'XmlElement' has no instance method 'findElements'.

### ISSUE THREAD

**Issue by fede1295** [renggli/dart-xml#105] opened 2021-05-20 15:35 UTC
XmlDocument.parse(bodyString).findAllElements('book'):

[        ] I/flutter (16952): NoSuchMethodError: Class 'XmlElement' has no instance method 'findElements'.
[        ] I/flutter (16952): Receiver: Instance of 'XmlElement'

findElements method  does not work .. has it been removed?
what can i use instead?

xml 5.1.0

[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.utf8)
    • Flutter version 2.0.6 at /home/federico/Flutter/Sdk/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

**Comment by renggli** [comment] 2021-05-20 16:36
It is here: https://github.com/renggli/dart-xml/blob/4744be75ee950acbede556187180568bce373600/lib/src/xml/navigation/find.dart#L14.

**Comment by geriby23** [comment] 2021-05-31 06:33
<img width="815" alt="Screenshot 2021-05-31 at 09 33 07" src="https://user-images.githubusercontent.com/29865863/120150030-36784f00-c1f3-11eb-8b16-ebd324f9cb3e.png">
Same issue here

**Comment by renggli** [comment] 2021-05-31 07:41
It works for me, see [the tests](https://github.com/renggli/dart-xml/blob/5.1.0/test/query_test.dart). 

How do your imports look like? Did you import the package correctly? 

```dart
import 'package:xml/xml.dart';
```

**Comment by renggli** [comment] 2021-08-14 09:12
Closing, as not reproducible.

**Closed by renggli** 2021-08-14 09:12 UTC
Labels: invalid
