### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: Class 'XmlDocument' has no instance method 'findElements'.

### ISSUE THREAD

**Issue by lekeCoder** [renggli/dart-xml#111] opened 2021-10-15 21:10 UTC
I have gone through the docs but it keep failing.

```
E/flutter ( 7910): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: Class 'XmlDocument' has no instance method 'findElements'.
E/flutter ( 7910): Receiver: Instance of 'XmlDocument'
E/flutter ( 7910): Tried calling: findElements("hymn")
```

xml: 5.3.0

```
[✓] Flutter (Channel stable, 2.5.2, on Mac OS X 10.15.7 19H1419 darwin-x64,
    locale en-US)
    • Flutter version 2.5.2 at /Users/SimplySwift/FlutterProjects/MACSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/SimplySwift/Library/Android/sdk
    • Platform android-31, build-tools 30.0.1
    • ANDROID_HOME = /Users/SimplySwift/Library/Android/sdk
    • Java binary at: /Users/SimplySwift/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

```

**Comment by renggli** [comment] 2021-10-16 07:52
The above code snippet works for me. 

How do your imports look like? If you write

```dart
import 'package:xml/xml.dart' show XmlDocument;
```

you are hiding all extension methods.

**Comment by lekeCoder** [comment] 2021-10-16 22:05
@renggli thanks for your responses. 

I imported `XmlDocument` using `import 'package:xml/xml.dart';` and the error still occur.  This is the error l get

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: Class 'XmlDocument' has no instance method 'findElements'.
Receiver: Instance of 'XmlDocument'
Tried calling: findElements("hymn")
```
I don't know what else l can do

**Comment by renggli** [comment] 2021-10-16 22:12
Can you provide a complete minimally reproducible runnable programm or test? I cannot reproduce the problem, neither in the tests nor in a separate program.

**Comment by renggli** [comment] 2021-11-09 21:24
I am closing this issue as I cannot reproduce the problem with the information provided.

**Closed by renggli** 2021-11-09 21:24 UTC
