### ISSUE TITLE
Cannot parse XML in a Flutter app

### ISSUE THREAD

**Issue by MaikuB** [renggli/dart-xml#42] opened 2018-04-23 13:20 UTC
Create a brand new Flutter app (beta 2, version 0.2.8), added in the sample code in the README file for reading XML and the following exception occurs

```
I/flutter ( 5573): type 'List<dynamic>' is not a subtype of type 'Iterable<XmlNode>' in type cast where
I/flutter ( 5573):   List is from dart:core
I/flutter ( 5573):   Iterable is from dart:core
I/flutter ( 5573):   XmlNode is from package:xml/xml/nodes/node.dart
```

**Comment by renggli** [comment] 2018-04-23 16:12
Thank you for the report. This is a duplicate of #38. Please make sure to update to at least `xml 3.0.0`, which is the first Dart 2.0 compatible version.

**Closed by renggli** 2018-04-23 16:12 UTC

**Comment by MaikuB** [comment] 2018-04-23 20:51
thanks for that, i was trying to use 3.0.0. I think what happened was I was using another package that depended on your library that was pulling an older version. When I removed that from the pubspec and just tried to pull your library to investigate, I think still resolved to an older version. Anyway, apologies about that, I'll nag the owner of the other package :)
