### ISSUE TITLE
XML parse blocking the UI

### ISSUE THREAD

**Issue by soska12** [renggli/dart-xml#68] opened 2020-01-21 10:19 UTC
I have a very big XML file about 50k+ element with in and for me on iOS the parse function looks like to hangs the UI of the application. A tried it out with a loading spinner and every time under the loading process it hangs for a while.
Also I tried it with flutters compute method and it produces the same for me.

Am I doing something very wrong? How should iI parse the xml file to a document in a correct way in the background not blocking any UI stuff in the foreground?

**Comment by renggli** [comment] 2020-01-21 12:04
Ultimately you should probably ask in a Flutter forum how to run and debug computationally expensive operations.

However, I suspect in your case the problem it is not only the time it takes to read the file, but also the size of the data. A typical solution is to use an event-based reader [xml_events.dart](https://github.com/renggli/dart-xml/blob/8917d6228668f9cbc355be1d17bef59831fd76cd/lib/xml_events.dart#L50) that can incrementally read the input and does not keep the complete document tree in memory.

If this is not an option, I recommend converting the XML file to a DB as part of the build process.

**Comment by PiN73** [comment] 2020-01-28 04:33
@soska12 [this approach](https://flutter.dev/docs/cookbook/networking/background-parsing#4-move-this-work-to-a-separate-isolate) works for me

**Comment by soska12** [comment] 2020-01-28 10:13
> @soska12 [this approach](https://flutter.dev/docs/cookbook/networking/background-parsing#4-move-this-work-to-a-separate-isolate) works for me

yes with small amount of that that works, but with a file with 600k+ lines it also freezes the UI when passing data back from isolate.

**Comment by PiN73** [comment] 2020-01-28 15:09
So if I understand correctly, the problem is not XML parsing but passing huge objects list.

In this case local database may be useful. I.e. isolate saves data to db after parsing, and then you query data on demand

**Comment by renggli** [comment] 2020-02-09 16:58
I am closing this issue, because &mdash; as far as I can understand &mdash; there is nothing I can do here.

**Closed by renggli** 2020-02-09 16:58 UTC
Labels: question
