### ISSUE TITLE
exception when parsing xml after updating to dart 2.0

### ISSUE THREAD

**Issue by ride4sun** [renggli/dart-xml#38] opened 2018-03-21 05:58 UTC
I am getting a parser exception with following string as content in the below 'staged' variable. This worked before the update to dart 2.0:

```
<InstantaneousDemand><DeviceMacId>0xd8d5b9000000b3e8</DeviceMacId><MeterMacId>0x00135003007c27b4</MeterMacId><TimeStamp>0x2244aeb3</TimeStamp><Demand>0x0006c1</Demand><Multiplier>0x00000001</Multiplier><Divisor>0x000003e8</Divisor><DigitsRight>0x03</DigitsRight><DigitsLeft>0x0f</DigitsLeft><SuppressLeadingZero>Y</SuppressLeadingZero></InstantaneousDemand>
```

this is the exception:
type 'List' is not a subtype of type 'Iterable<XmlNode>' in type cast where
  List is from dart:core
  Iterable is from dart:cor

 ```
Map<String, String> parseXMLResult(http.Response response) {
    final staged = response.body.replaceAll('\n', '').replaceAll(' ', ''); 
    final document = xml.parse('<?xml?>$staged');
    final result = <String, String>{};
...
```

C:\Projects\home_test>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.2.2-pre.2, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Community Edition (version 2017.2)
[√] VS Code, 32-bit edition (version 1.20.0)
[√] Connected devices (1 available)

• No issues found!

**Comment by renggli** [comment] 2018-03-21 07:11
Thank you for the bug report. I've added your example to the unit tests in d2812936009078b307177bfb5f5d375963c82edb. I've tested with Dart 2.0 (2.0.0-dev.40.0), Dart 2.0 (--preview-dart-2) and Flutter (0.2.4-pre.76, Dart 2.0.0-dev.39.0.flutter-06949dc985) but cannot reproduce a problem.

Could you provide the full stack trace of the exception, not just the error message?

**Comment by zoechi** [comment] 2018-03-21 09:45
Might be
```yaml
  strong-mode:
    implicit-casts: false
```
in `analysis_options.yaml`

**Comment by ride4sun** [comment] 2018-03-21 19:13
Thx Guenter for the hint. I changed my analyzer 'implicit-casts: false' to 'implicit-casts: true' but still see the exception. I provided the stacktrace below  :
``` 
strong-mode:
    declaration-casts: false
    implicit-casts: true
    implicit-dynamic: false
```

## Stacktrace
```
#0      Object._as (dart:core/object_patch.dart)
#1      XmlGrammarDefinition.element.<anonymous closure> (package:xml/xml/grammar.dart:126:43)
#2      ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:19:29)
#3      ChoiceParser.parseOn (package:petitparser/src/core/combinators/choice.dart:20:28)
#4      PossessiveRepeatingParser.parseOn (package:petitparser/src/core/repeaters/possesive.dart:28:29)
#5      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
#6      ChoiceParser.parseOn (package:petitparser/src/core/combinators/choice.dart:20:28)
#7      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
#8      ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:17:27)
#9      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
#10     ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:17:27)
#11     EndOfInputParser.parseOn (package:petitparser/src/core/combinators/eof.dart:16:27)
#12     Parser.parse (package:petitparser/src/core/parser.dart:48:26)
#13     parse (package:xml/xml.dart:40:24)
#14     PowerReader.parseXMLResult (package:home_test/eagle_gateway/power_reader.dart:71:26)
#15     PowerReader.readPower (package:home_test/eagle_gateway/power_reader.dart:36:16)
<asynchronous suspension>
#16     _LoginFormState._validateLoginInfoWithDevice (package:home_test/eagle_gateway/login_form.dart:102:65)
<asynchronous suspension>
#17     _LoginFormState._validate (package:home_test/eagle_gateway/login_form.dart:84:7)
#18     _LoginFormState.build.<anonymous closure> (package:home_test/eagle_gateway/login_form.dart:138:65)
#19     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
#20     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
#21     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#22     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#23     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
#24     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
#25     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#26     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#27     _BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
#28     _BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#29     _BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#30     _BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#31     _BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#32     _invoke1 (dart:ui/hooks.dart:134:13)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

**Comment by renggli** [comment] 2018-03-21 22:20
Are you sure that you are on `xml 3.0.0` version from pub? The last release with an `as` at position 126:43 is `xml 2.6.0` which is not strong mode compatible and would explain that error.

**Comment by ride4sun** [comment] 2018-03-21 22:37
Thats what I see under Dart Packages:
![capture](https://user-images.githubusercontent.com/7740651/37741188-a8c66d9e-2d1d-11e8-95fb-5580530e4eb8.PNG)

**Comment by ride4sun** [comment] 2018-03-21 22:39
Current stacktrace...
```
#0      Object._as (dart:core/object_patch.dart)
#1      XmlGrammarDefinition.element.<anonymous closure> (package:xml/xml/grammar.dart:126:43)
#2      ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:19:29)
#3      ChoiceParser.parseOn (package:petitparser/src/core/combinators/choice.dart:20:28)
#4      PossessiveRepeatingParser.parseOn (package:petitparser/src/core/repeaters/possesive.dart:28:29)
#5      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
#6      ChoiceParser.parseOn (package:petitparser/src/core/combinators/choice.dart:20:28)
#7      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
#8      ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:17:27)
#9      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
#10     ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:17:27)
#11     EndOfInputParser.parseOn (package:petitparser/src/core/combinators/eof.dart:16:27)
#12     Parser.parse (package:petitparser/src/core/parser.dart:48:26)
#13     parse (package:xml/xml.dart:40:24)
#14     PowerReader.parseXMLResult (package:home_test/eagle_gateway/power_reader.dart:71:26)
#15     PowerReader.readPower (package:home_test/eagle_gateway/power_reader.dart:36:16)
<asynchronous suspension>
#16     _LoginFormState._validateLoginInfoWithDevice (package:home_test/eagle_gateway/login_form.dart:102:65)
<asynchronous suspension>
#17     _LoginFormState._validate (package:home_test/eagle_gateway/login_form.dart:84:7)
#18     _LoginFormState.build.<anonymous closure> (package:home_test/eagle_gateway/login_form.dart:138:65)
#19     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
#20     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
#21     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#22     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#23     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
#24     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
#25     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#26     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#27     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
#28     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#29     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#30     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#31     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#32     _invoke1 (dart:ui/hooks.dart:134:13)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

**Comment by ride4sun** [comment] 2018-03-21 22:41
I did run ur test in your git cml project and they pass

**Comment by zoechi** [comment] 2018-03-22 04:12
If you get a runtime exception, it's not related to `analysis_options.yaml`.
I misinterpreted the initial post.

**Comment by renggli** [comment] 2018-03-22 17:24
I cannot reproduce the error: neither with any of the latest runtimes, nor with your `analysis_options.yaml` config. Only way I can reproduce the problem is by reverting back to `xml 2.6.0`, where I get the reported stack trace:

```
Unhandled exception:
type 'List' is not a subtype of type 'Iterable<XmlNode>' in type cast where
  List is from dart:core
  Iterable is from dart:core
  XmlNode is from package:xml/xml/nodes/node.dart

#0      Object._as (dart:core/runtime/libobject_patch.dart)
#1      XmlGrammarDefinition.element.<anonymous closure> (package:xml/xml/grammar.dart:126:43)
#2      ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:19:29)
#3      ChoiceParser.parseOn (package:petitparser/src/core/combinators/choice.dart:20:28)
...
```

**Comment by renggli** [comment] 2018-03-27 07:03
Is this still an open issue?

**Comment by ride4sun** [comment] 2018-03-27 16:52
I will check again and report.

**Comment by lemonboston** [comment] 2018-04-03 21:11
I've got that exception too now with 3.0.0:
```
    type 'List' is not a subtype of type 'Iterable<XmlNode>' in type cast where
      List is from dart:core
      Iterable is from dart:core
      XmlNode is from package:xml/xml/nodes/node.dart
    
    #0      Object._as (dart:core/object_patch.dart)
    #1      XmlGrammarDefinition.element.<anonymous closure> (package:xml/xml/grammar.dart:126:43)
    #2      ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:19:29)
    #3      ChoiceParser.parseOn (package:petitparser/src/core/combinators/choice.dart:20:28)
    #4      PossessiveRepeatingParser.parseOn (package:petitparser/src/core/repeaters/possesive.dart:28:29)
    #5      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
    #6      ChoiceParser.parseOn (package:petitparser/src/core/combinators/choice.dart:20:28)
    #7      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
    #8      ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:17:27)
    #9      SequenceParser.parseOn (package:petitparser/src/core/combinators/sequence.dart:21:32)
    #10     ActionParser.parseOn (package:petitparser/src/core/actions/action.dart:17:27)
    #11     EndOfInputParser.parseOn (package:petitparser/src/core/combinators/eof.dart:16:27)
    #12     Parser.parse (package:petitparser/src/core/parser.dart:48:26)
    #13     parse (package:xml/xml.dart:40:24)
```
Line 126 in the source:
```dart
if (list[4] == CLOSE_END_ELEMENT) {
```

**Comment by ctac1287** [comment] 2018-04-04 04:30
I also have a similar error with 3.0.0:

type 'List<dynamic>' is not a subtype of type 'Iterable<XmlNode>' in type cast where
  List is from dart:core
  Iterable is from dart:core
  XmlNode is from package:xml/xml/nodes/node.dart

**Comment by renggli** [comment] 2018-04-04 11:43
I am puzzled: the error is caused by `as`, but as you state there is no such thing in version 3.0.0 on line 126 (however, there is in 2.6.0). 

I've already spend hours trying to reproduce the problem in HEAD but cannot with various fart versions. Can somebody please provide a test case in HEAD and a command line, so that I can reproduce on my machine?

**Comment by zoechi** [comment] 2018-04-04 19:48
I get some errors only after `flutter clean` (just a wild guess)

**Comment by ctac1287** [comment] 2018-04-05 03:21
May be this will help you ?
[data.txt](https://github.com/renggli/dart-xml/files/1878462/data.txt)

**Comment by renggli** [comment] 2018-04-08 07:32
Thanks, I am closing the issue then.

**Closed by renggli** 2018-04-08 07:32 UTC
